void init_roomba(void);
void purchase_roomba(void);
void roomba(void);
int get_roomba_strength(void);
void add_roomba_strength(int add_roomba);
void add_roomba_speed(int add_roomba_speed);
void minus_roomba_strength(int minus_roomba);
int roomba_purchase(void);
int get_closest_dirt_index(void);
int get_roomba_currently_scrubbing(void);
float get_roomba_x(void); 
float get_roomba_y(void);
float get_roomba_speed(void);
void sell_roomba(void);