void InitRoomba(void);
void PurchaseRoomba(void);
void RoombaFunction(void);
int GetRoombaStrength(void);
void AddRoombaStrength(int add_roomba);
void AddRoombaSpeed(int AddRoombaSpeed);
void MinusRoombaStrength(int minus_roomba);
int roomba_purchase(void);
int get_closest_dirt_index(void);
int get_roomba_currently_scrubbing(void);
float get_roomba_x(void); 
float get_roomba_y(void);
float get_roomba_speed(void);
void ResetRoomba(void);